In [2]:
import pandas as pd

In [3]:
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

In [184]:
player_stats = pd.read_csv("doncic.csv", index_col=0)

In [185]:
player_stats

,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,GS,MP,...,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-,PlayerCode
0,1,1,2022-10-19,27-324,NYK,@,MEM,L (-3),1,34:55,...,11,6,2,0,3,6,24,20.9,+7,d/doncilu01
1,2,2,2022-10-21,27-326,NYK,NaN,DET,W (+24),1,25:27,...,6,0,0,0,0,2,15,9.6,-1,d/doncilu01
2,3,3,2022-10-24,27-329,NYK,NaN,ORL,W (+13),1,34:07,...,12,4,1,0,2,5,25,19.9,+4,d/doncilu01
3,4,4,2022-10-26,27-331,NYK,NaN,CHO,W (+3),1,39:50,...,6,2,2,1,1,5,17,9.8,+6,d/doncilu01
4,5,5,2022-10-28,27-333,NYK,@,MIL,L (-11),1,31:14,...,12,2,1,0,3,4,14,10.8,-14,d/doncilu01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,79,NaN,2023-04-02,28-124,NYK,NaN,WAS,W (+9),Inactive,Inactive,...,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,d/doncilu01
82,80,NaN,2023-04-05,28-127,NYK,@,IND,W (+9),Inactive,Inactive,...,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,d/doncilu01
83,Rk,G,Date,Age,Tm,NaN,Opp,NaN,GS,MP,...,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-,d/doncilu01
84,81,NaN,2023-04-07,28-129,NYK,@,NOP,L (-8),Inactive,Inactive,...,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,d/doncilu01
85,82,NaN,2023-04-09,28-131,NYK,NaN,IND,L (-5),Inactive,Inactive,...,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,Inactive,d/doncilu01

In [186]:
player_stats.drop(['Rk', 'G', 'Date', 'Age', 'Unnamed: 7','GS','FG','FGA','FG%', '...', ' FT%', 'ORB', 'DRB', 'STL', 'BLK','FT','TOB', 'PF'], inplace=True, axis=1, errors='ignore')

In [187]:
p_stats = player_stats.loc[player_stats['PTS'] != "Inactive"]
p_stats = p_stats[p_stats['PTS'] != 'Player Suspended']
p_stats = p_stats[p_stats['PTS'] != 'PTS']
p_stats = p_stats[p_stats['PTS'] != 'Did Not Dress']
p_stats = p_stats[p_stats['PTS'] != 'Did Not Play']
p_stats = p_stats[p_stats['PTS'] != 'Not With Team']
p_stats = p_stats[p_stats['PTS'] != 'TRB']

In [188]:
p_stats

,Tm,Unnamed: 5,Opp,MP,3P,3PA,3P%,FTA,FT%,TRB,AST,TOV,PTS,GmSc,+/-,PlayerCode
0,NYK,@,MEM,34:55,2,6,.333,5,.800,11,6,3,24,20.9,+7,d/doncilu01
1,NYK,NaN,DET,25:27,2,3,.667,4,.750,6,0,0,15,9.6,-1,d/doncilu01
2,NYK,NaN,ORL,34:07,2,9,.222,5,.600,12,4,2,25,19.9,+4,d/doncilu01
3,NYK,NaN,CHO,39:50,0,2,.000,4,.750,6,2,1,17,9.8,+6,d/doncilu01
4,NYK,@,MIL,31:14,0,2,.000,9,.889,12,2,3,14,10.8,-14,d/doncilu01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,NYK,NaN,MIN,36:53,8,14,.571,13,.846,4,1,4,57,39.8,-6,d/doncilu01
76,NYK,@,MIA,35:59,1,5,.200,1,.000,6,9,4,15,9.3,-6,d/doncilu01
77,NYK,@,ORL,35:38,2,9,.222,10,.700,9,4,1,23,14.9,+20,d/doncilu01
78,NYK,NaN,HOU,28:16,3,8,.375,3,1.000,4,3,1,26,20.0,+11,d/doncilu01
79,NYK,NaN,MIA,14:42,0,2,.000,2,.500,5,1,2,3,0.1,-3,d/doncilu01

In [189]:
p_stats['PTS'] = p_stats['PTS'].astype(float)

In [190]:
p_stats['PTS'] = p_stats['PTS'].astype(int)

In [191]:
p_stats

,Tm,Unnamed: 5,Opp,MP,3P,3PA,3P%,FTA,FT%,TRB,AST,TOV,PTS,GmSc,+/-,PlayerCode
0,NYK,@,MEM,34:55,2,6,.333,5,.800,11,6,3,24,20.9,+7,d/doncilu01
1,NYK,NaN,DET,25:27,2,3,.667,4,.750,6,0,0,15,9.6,-1,d/doncilu01
2,NYK,NaN,ORL,34:07,2,9,.222,5,.600,12,4,2,25,19.9,+4,d/doncilu01
3,NYK,NaN,CHO,39:50,0,2,.000,4,.750,6,2,1,17,9.8,+6,d/doncilu01
4,NYK,@,MIL,31:14,0,2,.000,9,.889,12,2,3,14,10.8,-14,d/doncilu01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,NYK,NaN,MIN,36:53,8,14,.571,13,.846,4,1,4,57,39.8,-6,d/doncilu01
76,NYK,@,MIA,35:59,1,5,.200,1,.000,6,9,4,15,9.3,-6,d/doncilu01
77,NYK,@,ORL,35:38,2,9,.222,10,.700,9,4,1,23,14.9,+20,d/doncilu01
78,NYK,NaN,HOU,28:16,3,8,.375,3,1.000,4,3,1,26,20.0,+11,d/doncilu01
79,NYK,NaN,MIA,14:42,0,2,.000,2,.500,5,1,2,3,0.1,-3,d/doncilu01

In [192]:
p_stats.dtypes

Tm            object
Unnamed: 5    object
Opp           object
MP            object
3P            object
3PA           object
3P%           object
FTA           object
FT%           object
TRB           object
AST           object
TOV           object
PTS            int32
GmSc          object
+/-           object
PlayerCode    object
dtype: object

In [193]:
p_stats["target"] = (p_stats["PTS"] >= 30).astype("int")

In [194]:
p_stats["opp_code"] = p_stats["Opp"].astype("category").cat.codes

In [195]:
p_stats['away'] =  p_stats['Unnamed: 5'].isna()

In [196]:
p_stats ['away'] = p_stats['away'].astype(int)

In [197]:
p_stats['3ptbefore'] = p_stats["3P"].shift(1)

In [198]:
p_stats ['day_before'] = p_stats["PTS"].shift(1)
p_stats['day_before'] = (p_stats['day_before'] < 25).astype("int")

In [199]:
p_stats=p_stats.fillna(0)

In [200]:
p_stats

,Tm,Unnamed: 5,Opp,MP,3P,3PA,3P%,FTA,FT%,TRB,...,TOV,PTS,GmSc,+/-,PlayerCode,target,opp_code,away,3ptbefore,day_before
0,NYK,@,MEM,34:55,2,6,.333,5,.800,11,...,3,24,20.9,+7,d/doncilu01,0,14,0,0,0
1,NYK,0,DET,25:27,2,3,.667,4,.750,6,...,0,15,9.6,-1,d/doncilu01,0,8,1,2,1
2,NYK,0,ORL,34:07,2,9,.222,5,.600,12,...,2,25,19.9,+4,d/doncilu01,0,20,1,2,1
3,NYK,0,CHO,39:50,0,2,.000,4,.750,6,...,1,17,9.8,+6,d/doncilu01,0,4,1,2,0
4,NYK,@,MIL,31:14,0,2,.000,9,.889,12,...,3,14,10.8,-14,d/doncilu01,0,16,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,NYK,0,MIN,36:53,8,14,.571,13,.846,4,...,4,57,39.8,-6,d/doncilu01,1,17,1,1,1
76,NYK,@,MIA,35:59,1,5,.200,1,.000,6,...,4,15,9.3,-6,d/doncilu01,0,15,0,8,0
77,NYK,@,ORL,35:38,2,9,.222,10,.700,9,...,1,23,14.9,+20,d/doncilu01,0,20,0,1,1
78,NYK,0,HOU,28:16,3,8,.375,3,1.000,4,...,1,26,20.0,+11,d/doncilu01,0,10,1,2,1
79,NYK,0,MIA,14:42,0,2,.000,2,.500,5,...,2,3,0.1,-3,d/doncilu01,0,15,1,3,0

In [201]:
from sklearn.ensemble import RandomForestClassifier

In [202]:
rf = RandomForestClassifier(n_estimators=20, min_samples_split=10, random_state=2)

In [203]:
train = p_stats[0:40]

In [204]:
test = p_stats[40:]

In [205]:
predictors = ["opp_code", "away", "day_before","3ptbefore"]

In [206]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=20, random_state=2)

In [207]:
preds = rf.predict(test[predictors])

In [208]:
from sklearn.metrics import accuracy_score

In [215]:
p_acerto = accuracy_score(test["target"], preds)

In [216]:
p_acerto

0.6756756756756757

In [217]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [218]:
combined

    actual  predicted
42       0          0
43       0          0
44       0          0
45       1          0
46       0          0
47       0          1
48       1          0
49       0          1
50       1          0
51       1          1
52       0          1
53       0          0
54       0          0
55       0          0
56       0          0
57       0          0
58       1          0
59       1          1
60       0          0
61       0          1
63       1          1
64       0          0
65       0          0
66       0          0
67       1          0
68       1          1
69       0          0
70       0          0
71       0          0
72       1          0
73       0          0
74       0          0
75       1          0
76       0          1
77       0          0
78       0          0
79       0          0

In [219]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted   0  1
actual
0          21  5
1           7  4

In [33]:
test1 = test[test['away'] == 1]

In [210]:
test

,Tm,Unnamed: 5,Opp,MP,3P,3PA,3P%,FTA,FT%,TRB,...,TOV,PTS,GmSc,+/-,PlayerCode,target,opp_code,away,3ptbefore,day_before
42,NYK,0,MIL,39:46,1,12,.083,7,.857,16,...,3,25,16.8,+2,a/antetgi01,1,16,1,6,0
43,NYK,0,IND,38:33,2,7,.286,4,.500,16,...,6,14,9.5,+9,a/antetgi01,0,11,1,1,0
44,NYK,@,WAS,35:48,2,6,.333,8,.625,16,...,3,23,15.3,+12,a/antetgi01,0,28,0,2,1
45,NYK,@,DET,40:08,4,7,.571,8,1.000,15,...,1,42,37.8,+14,a/antetgi01,1,8,0,2,1
46,NYK,0,TOR,42:00,1,6,.167,9,.667,15,...,3,21,16.7,+1,a/antetgi01,0,26,1,4,0
47,NYK,0,WAS,34:04,0,5,.000,5,.400,15,...,2,14,10.4,-11,a/antetgi01,0,28,1,1,1
48,NYK,@,ATL,33:18,3,10,.300,9,.778,9,...,3,32,24.1,-12,a/antetgi01,1,0,0,0,1
49,NYK,@,TOR,37:29,2,6,.333,8,.625,19,...,4,23,22.5,-4,a/antetgi01,0,26,0,3,0
50,NYK,0,CLE,37:38,8,12,.667,7,.857,13,...,5,36,27.4,-10,a/antetgi01,1,5,1,2,1
51,NYK,@,BOS,36:54,5,13,.385,7,.857,9,...,2,37,24.8,-16,a/antetgi01,1,1,0,8,0
52,NYK,@,BRK,38:14,1,6,.167,6,.667,10,...,3,19,16.4,+6,a/antetgi01,0,2,0,5,0
53,NYK,0,LAL,43:01,2,9,.222,11,.818,12,...,4,23,13.6,-9,a/antetgi01,0,13,1,1,1
54,NYK,0,MIA,34:20,3,9,.333,5,.800,10,...,7,23,14.5,+14,a/antetgi01,0,15,1,2,1
55,NYK,0,LAC,40:44,2,6,.333,8,.750,11,...,5,28,20.8,-11,a/antetgi01,1,12,1,3,1
56,NYK,0,PHI,34:08,1,8,.125,8,.875,9,...,3,24,18.9,-6,a/antetgi01,0,21,1,2,0
57,NYK,@,ORL,34:06,4,10,.400,6,.667,14,...,4,22,17.5,+9,a/antetgi01,0,20,0,1,1
58,NYK,@,PHI,36:33,5,11,.455,3,1.000,10,...,3,30,22.1,-6,a/antetgi01,1,21,0,4,1
59,NYK,0,UTA,38:58,3,11,.273,5,.800,6,...,1,31,19.0,+4,a/antetgi01,1,27,1,5,0
60,NYK,0,BRK,32:20,1,6,.167,3,1.000,10,...,1,18,15.0,+14,a/antetgi01,0,2,1,3,0
61,NYK,@,ATL,34:50,3,8,.375,5,.800,11,...,3,25,16.2,+20,a/antetgi01,1,0,0,1,1
63,NYK,@,WAS,36:11,7,14,.500,7,1.000,2,...,1,46,34.7,+8,a/antetgi01,1,28,0,3,0
64,NYK,0,NOP,32:36,5,10,.500,1,1.000,7,...,2,28,22.0,+26,a/antetgi01,1,18,1,7,0
65,NYK,0,BOS,35:53,3,9,.333,9,.667,7,...,1,23,16.9,+8,a/antetgi01,0,1,1,5,0
66,NYK,0,BRK,35:04,4,8,.500,5,.600,8,...,4,21,15.3,+27,a/antetgi01,0,2,1,3,1
67,NYK,@,MIA,35:47,8,13,.615,4,.750,9,...,3,43,33.2,+1,a/antetgi01,1,15,0,4,1
68,NYK,@,BOS,46:31,5,13,.385,4,1.000,9,...,7,31,18.3,-8,a/antetgi01,1,1,0,8,0
69,NYK,0,CHO,35:11,2,9,.222,6,.667,8,...,2,16,6.6,-20,a/antetgi01,0,4,1,5,0
70,NYK,@,SAC,36:17,2,12,.167,9,.556,10,...,4,23,12.1,-4,a/antetgi01,0,24,0,2,1
71,NYK,@,LAC,34:40,3,10,.300,8,.750,8,...,2,19,4.3,-8,a/antetgi01,0,12,0,2,1
72,NYK,@,LAL,35:46,3,12,.250,11,.727,8,...,3,33,22.9,-1,a/antetgi01,1,13,0,3,1
73,NYK,@,POR,33:50,0,5,.000,10,.800,10,...,2,24,15.4,+8,a/antetgi01,0,23,0,3,0
74,NYK,0,DEN,36:19,1,6,.167,7,1.000,7,...,3,20,14.0,+5,a/antetgi01,0,7,1,0,1
75,NYK,0,MIN,36:53,8,14,.571,13,.846,4,...,4,57,39.8,-6,a/antetgi01,1,17,1,1,1
76,NYK,@,MIA,35:59,1,5,.200,1,.000,6,...,4,15,9.3,-6,a/antetgi01,0,15,0,8,0
77,NYK,@,ORL,35:38,2,9,.222,10,.700,9,...,1,23,14.9,+20,a/antetgi01,0,20,0,1,1
78,NYK,0,HOU,28:16,3,8,.375,3,1.000,4,...,1,26,20.0,+11,a/antetgi01,1,10,1,2,1
79,NYK,0,MIA,14:42,0,2,.000,2,.500,5,...,2,3,0.1,-3,a/antetgi01,0,15,1,3,0

In [ ]:
predicao = {'Tm': 'NYK', 'Opp': 'LAL', 'MP': '38:54','opp_code': '21', 'away': '0', 'target': '0', 'TRB': '0'}

In [ ]:
test.loc[200] = ['Segunda-Feira','2023-12-18','0','0','0', 1, 1, 0,20,0, 10.000]

In [ ]:
test1 = test1.append(predicao, ignore_index=True)

In [ ]:
test1

In [ ]:
test1=test1.fillna("1")

In [ ]:
test1